dist: xenial
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential libopenmpi-dev 


language: python

python:
  - "3.7-dev"  # 3.7 development branch

install:
  - pip install codecov
  - pip install scipy
  - pip install coverage
  - pip install pyyaml
  # - pip install mpi4py

script:
  - coverage run tests.py

after_success:
  - codecov
